name: hwyd
description: hwyd is a simple journaling app that asks only one question - how was your day? - and leaves the rest to you
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/hwyd_logo.png
  uses-material-design: true
